spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ORCA_LOCAL_DB_HOST:localhost}:${ORCA_LOCAL_DB_PORT:3306}/${ORCA_LOCAL_DB_NAME:orca}
    username: ${ORCA_LOCAL_DB_USERNAME}
    password: ${ORCA_LOCAL_DB_PASSWORD}

server:
  port: ${ORCA_LOCAL_BACKEND_PORT:8080}
